### ISSUE TITLE
[Makefile:116: lib/libft/libft.a] Error 2

### ISSUE THREAD

**Issue by Petross404** [arwn/corewar#1]
Hi there, I clone corewar to build and experiment with it but I have problem compiling it.

I am running `make deps` as advised in the README file but all I get is this error:
```
make deps
make -C lib/libft/ all
make[1]: Entering directory '/mnt/Volume_3/Gentoo/projects/RE/corewar_/lib/libft'
make[1]: *** No rule to make target 'all'.  Stop.
make[1]: Leaving directory '/mnt/Volume_3/Gentoo/projects/RE/corewar_/lib/libft'
make: *** [Makefile:116: lib/libft/libft.a] Error 2
```
Altough I have installed the dependencies glfw and glew.

What am I missing here? Thank you.

**Comment by arwn** [comment]
you probably didn't clone the submodules. is the lib/libft directory populated?

**Comment by Petross404** [comment]
> you probably didn't clone the submodules. is the lib/libft directory populated?

Yes, you are right, I didn't clone them. 
So are these dependencies optional, I mean can one use dependencies and libraries that are installed on the system?

**Comment by arwn** [comment]
In theory, yes. however I haven't tried. (the mac I was using didn't allow users to install software).
